project:
  type: book
  output-dir: docs
  output-file: "DeBruine-30DCC-2022"
  resources: 
  - "images/*"
  - "data/*"

book:
  title: "30DCC (2022)"
  author: "Lisa DeBruine"
  description: "Code and charts for the 2022 30-Day Chart Challenge"
  cover-image: images/logos/logo.png
  image: images/logos/logo.png
  fav-icon: images/logos/favicon.ico
  #cookie-consent: true
  google-analytics: "G-6NP3MF25W3"
  page-navigation: true
  search: true
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
  repo-url: https://github.com/debruine/30DCC-2022/
  repo-actions: [edit, issue, source]
#  downloads: [pdf, epub]
  sharing: [twitter, facebook, linkedin]
  # sidebar:
  #   style: docked
  #   background: light
  page-footer: 
    left: "CC-BY 2022, Lisa DeBruine" 
    right: 
      - icon: github
        href: https://github.com/debruine/30DCC-2022
      - icon: twitter 
        href: https://twitter.com/lisadebruine
  chapters:
    - index.qmd
    - part: "Comparisons"
      chapters:
      - 01-part-to-whole.qmd
      - 02-pictogram.qmd
      - 03-historical.qmd
      - 04-flora.qmd
      - 05-slope.qmd
      - 06-owid.qmd
    - part: "Distributions"
      chapters:
      - 07-physical.qmd
      - 08-mountains.qmd
      - 09-statistics.qmd
      - 10-experimental.qmd
      - 11-circular.qmd
      - 12-economist.qmd
    - part: "Relationships"
      chapters:
      - 13-correlation.qmd
      - 14-3-dimensional.qmd
      - 15-multivariate.qmd
      - 16-environment.qmd
      - 17-connections.qmd
      - 18-oecd.qmd
    - part: "Timeseries"
      chapters:
      - 19-global-change.qmd
      - 20-new-tool.qmd
      - 21-down-upwards.qmd
      - 22-animation.qmd
      - 23-tiles.qmd
      - 24-financial-times.qmd
    - part: "Uncertainties"
      chapters:
      - 25-trend.qmd
      - 26-interactive.qmd
      - 27-future.qmd
      - 28-deviations.qmd
      - 29-storytelling.qmd
      - 30-un-population.qmd
  appendices:
    - app-a-colours.qmd
    - app-b-stained-glass.qmd
    - app-c-magic-eye.qmd
    - app-d-psyarxiv.qmd

bibliography: include/book.bib
csl: include/apa.csl

format:
  html:
    theme: default
    code-link: true
    code-fold: true
    code-line-numbers: true
    code-overflow: wrap
    code-copy: true
    # code-block-border-left: "#4864DB"
    highlight-style: a11y
    # monofont: Fira Code
    # mainfont: Open Sans
    css: include/style.css
    include-after-body: include/script.js
  pdf:
    documentclass: scrreprt
    include-in-header: include/preamble.tex
  epub: default



